Fixes collision/prototype change with octave 5.x
"octave_value get_global_value ()" is declared in Octave headers, there is no need to repeat it as extern.

The actual error message is as below:

---
Octave.C:46:21: error: default argument given for parameter 2 of ‘octave_value get_global_value(const string&, bool)’ [-fpermissive]
   46 | extern octave_value get_global_value (const string& nm, bool silent = false);
      |                     ^~~~~~~~~~~~~~~~
In file included from /usr/include/octave-5.1.0/octave/../octave/hook-fcn.h:33,
                 from /usr/include/octave-5.1.0/octave/../octave/input.h:34,
                 from /usr/include/octave-5.1.0/octave/../octave/lex.h:34,
                 from /usr/include/octave-5.1.0/octave/../octave/parse.h:36,
                 from Octave.C:18:
/usr/include/octave-5.1.0/octave/../octave/variables.h:144:1: note: previous specification in ‘octave_value get_global_value(const string&, bool)’ here
  144 | get_global_value (const std::string& nm, bool silent = false);
      | ^~~~~~~~~~~~~~~~
---

Fixes https://github.com/flatmax/gtkiostream/issues/4